# Generated by Django 5.2.7 on 2026-01-10 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="employee",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="employee.employee",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="blacklistedtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blacklisted_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="blacklistedtoken",
            index=models.Index(fields=["jti"], name="blacklisted_jti_10baef_idx"),
        ),
        migrations.AddIndex(
            model_name="blacklistedtoken",
            index=models.Index(
                fields=["user", "blacklisted_at"], name="blacklisted_user_id_6f7037_idx"
            ),
        ),
    ]
