# Generated by Django 5.2.7 on 2026-08-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinvitation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userinvitation',
            new_name='accounts_us_token_15d7e5_idx',
            old_name='accounts_ui_token_idx',
        ),
        migrations.RenameIndex(
            model_name='userinvitation',
            new_name='accounts_us_email_d01203_idx',
            old_name='accounts_ui_email_idx',
        ),
        migrations.RenameIndex(
            model_name='userinvitation',
            new_name='accounts_us_status_bb7459_idx',
            old_name='accounts_ui_status_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Avatar'),
        ),
    ]
