# Generated by Django 5.2.7 on 2026-01-10 11:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgetline", "0001_initial"),
        ("employee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GRADUACAO", "Graduação"),
                            ("POS_GRADUACAO", "Pós-Graduação"),
                            ("AUXILIO_CHECHE_ESCOLA", "Auxílio Creche Escola"),
                            ("LINGUA_ESTRANGEIRA", "Língua Estrangeira"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "installment_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número de Parcelas"
                    ),
                ),
                (
                    "amount_per_installment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor por Parcela",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data de Início")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Término"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando Início"),
                            ("ATIVO", "Ativo"),
                            ("CONCLUIDO", "Concluído"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="AGUARDANDO",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "budget_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistances",
                        to="budgetline.budgetline",
                        verbose_name="Linha Orçamentária",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_assistances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistances",
                        to="employee.employee",
                        verbose_name="Funcionário",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_assistances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistência",
                "verbose_name_plural": "Assistências",
                "ordering": ["start_date"],
            },
        ),
    ]
