# Generated by Django 5.2 on 2026-01-20 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0001_initial'),
        ('budget', '0002_add_cached_amount_fields'),
        ('budgetline', '0003_budgetline_available_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='budget.budget', verbose_name='Orçamento'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='budgetline.budgetline', verbose_name='Linha Orçamentária'),
        ),
    ]
