# Generated by Django 5.2.7 on 2026-01-10 11:24

import accounts.permissions
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budget", "0001_initial"),
        ("center", "0001_initial"),
        ("employee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("CAPEX", "CAPEX"), ("OPEX", "OPEX")],
                        max_length=100,
                        null=True,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("Base Principal", "Base Principal"),
                            ("Serviços Especializados", "Serviços Especializados"),
                            ("Despesas Compartilhadas", "Despesas Compartilhadas"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Despesa",
                    ),
                ),
                (
                    "summary_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descrição resumida",
                    ),
                ),
                (
                    "object",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="Objeto"
                    ),
                ),
                (
                    "budget_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NOVO", "NOVO"),
                            ("RENOVAÇÃO", "RENOVAÇÃO"),
                            ("CARY OVER", "CARY OVER"),
                            ("REPLANEJAMENTO", "REPLANEJAMENTO"),
                            ("N/A", "N/A"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Classificação Orçamentária",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SERVIÇO", "SERVIÇO"),
                            ("FORNECIMENTO", "FORNECIMENTO"),
                            ("ASSINATURA", "ASSINATURA"),
                            ("FORNECIMENTO/SERVIÇO", "FORNECIMENTO/SERVIÇO"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de Contrato",
                    ),
                ),
                (
                    "probable_procurement_type",
                    models.CharField(
                        choices=[
                            ("LICITAÇÃO", "LICITAÇÃO"),
                            (
                                "DISPENSA EM RAZÃO DO VALOR",
                                "DISPENSA EM RAZÃO DO VALOR",
                            ),
                            ("CONVÊNIO", "CONVÊNIO"),
                            ("FUNDO FIXO", "FUNDO FIXO"),
                            ("INEXIGIBILIDADE", "INEXIGIBILIDADE"),
                            ("ATA DE REGISTRO DE PREÇO", "ATA DE REGISTRO DE PREÇO"),
                            ("ACORDO DE COOPERAÇÃO", "ACORDO DE COOPERAÇÃO"),
                            ("APOSTILAMENTO", "APOSTILAMENTO"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Aquisição",
                    ),
                ),
                (
                    "budgeted_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Valor Orçado",
                    ),
                ),
                (
                    "process_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VENCIDO", "VENCIDO"),
                            ("DENTRO DO PRAZO", "DENTRO DO PRAZO"),
                            ("ELABORADO COM ATRASO", "ELABORADO COM ATRASO"),
                            ("ELABORADO NO PRAZO", "ELABORADO NO PRAZO"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Status do Processo",
                    ),
                ),
                (
                    "contract_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DENTRO DO PRAZO", "DENTRO DO PRAZO"),
                            ("CONTRATADO NO PRAZO", "CONTRATADO NO PRAZO"),
                            ("CONTRATADO COM ATRASO", "CONTRATADO COM ATRASO"),
                            ("PRAZO VENCIDO", "PRAZO VENCIDO"),
                            (
                                "LINHA TOTALMENTE REMANEJADA",
                                "LINHA TOTALMENTE REMANEJADA",
                            ),
                            (
                                "LINHA TOTALMENTE EXECUTADA",
                                "LINHA TOTALMENTE EXECUTADA",
                            ),
                            ("LINHA DE PAGAMENTO", "LINHA DE PAGAMENTO"),
                            (
                                "LINHA PARCIALMENTE REMANEJADA",
                                "LINHA PARCIALMENTE REMANEJADA",
                            ),
                            (
                                "LINHA PARCIALMENTE EXECUTADA",
                                "LINHA PARCIALMENTE EXECUTADA",
                            ),
                            ("N/A", "N/A"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Status do Contrato",
                    ),
                ),
                (
                    "contract_notes",
                    models.TextField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_lines",
                        to="budget.budget",
                        verbose_name="Orçamento",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_lines_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "main_fiscal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="main_contract_fiscal",
                        to="employee.employee",
                        verbose_name="Fiscal Principal",
                    ),
                ),
                (
                    "management_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_lines",
                        to="center.managementcenter",
                        verbose_name="Centro de Gestor",
                    ),
                ),
                (
                    "requesting_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="center.requestingcenter",
                        verbose_name="Centro Solicitante",
                    ),
                ),
                (
                    "secondary_fiscal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secondary_contract_fiscal",
                        to="employee.employee",
                        verbose_name="Fiscal Substituto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_lines_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha Orçamentária",
                "verbose_name_plural": "Linhas Orçamentárias",
                "ordering": ["-created_at"],
            },
            bases=(models.Model, accounts.permissions.HierarchicalPermissionMixin),
        ),
        migrations.CreateModel(
            name="BudgetLineMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Valor da Movimentação",
                    ),
                ),
                (
                    "movement_notes",
                    models.TextField(
                        blank=True, max_length=400, null=True, verbose_name="Motivo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_line_movements_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "destination_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_movements",
                        to="budgetline.budgetline",
                        verbose_name="Linha de Destino",
                    ),
                ),
                (
                    "source_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_movements",
                        to="budgetline.budgetline",
                        verbose_name="Linha de Origem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_line_movements_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLineVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Número da Versão"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("CAPEX", "CAPEX"), ("OPEX", "OPEX")],
                        max_length=100,
                        null=True,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("Base Principal", "Base Principal"),
                            ("Serviços Especializados", "Serviços Especializados"),
                            ("Despesas Compartilhadas", "Despesas Compartilhadas"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Despesa",
                    ),
                ),
                (
                    "summary_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descrição resumida",
                    ),
                ),
                (
                    "object",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="Objeto"
                    ),
                ),
                (
                    "budget_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NOVO", "NOVO"),
                            ("RENOVAÇÃO", "RENOVAÇÃO"),
                            ("CARY OVER", "CARY OVER"),
                            ("REPLANEJAMENTO", "REPLANEJAMENTO"),
                            ("N/A", "N/A"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Classificação Orçamentária",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SERVIÇO", "SERVIÇO"),
                            ("FORNECIMENTO", "FORNECIMENTO"),
                            ("ASSINATURA", "ASSINATURA"),
                            ("FORNECIMENTO/SERVIÇO", "FORNECIMENTO/SERVIÇO"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de Contrato",
                    ),
                ),
                (
                    "probable_procurement_type",
                    models.CharField(
                        choices=[
                            ("LICITAÇÃO", "LICITAÇÃO"),
                            (
                                "DISPENSA EM RAZÃO DO VALOR",
                                "DISPENSA EM RAZÃO DO VALOR",
                            ),
                            ("CONVÊNIO", "CONVÊNIO"),
                            ("FUNDO FIXO", "FUNDO FIXO"),
                            ("INEXIGIBILIDADE", "INEXIGIBILIDADE"),
                            ("ATA DE REGISTRO DE PREÇO", "ATA DE REGISTRO DE PREÇO"),
                            ("ACORDO DE COOPERAÇÃO", "ACORDO DE COOPERAÇÃO"),
                            ("APOSTILAMENTO", "APOSTILAMENTO"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Aquisição",
                    ),
                ),
                (
                    "budgeted_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Valor Orçado",
                    ),
                ),
                (
                    "process_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VENCIDO", "VENCIDO"),
                            ("DENTRO DO PRAZO", "DENTRO DO PRAZO"),
                            ("ELABORADO COM ATRASO", "ELABORADO COM ATRASO"),
                            ("ELABORADO NO PRAZO", "ELABORADO NO PRAZO"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Status do Processo",
                    ),
                ),
                (
                    "contract_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DENTRO DO PRAZO", "DENTRO DO PRAZO"),
                            ("CONTRATADO NO PRAZO", "CONTRATADO NO PRAZO"),
                            ("CONTRATADO COM ATRASO", "CONTRATADO COM ATRASO"),
                            ("PRAZO VENCIDO", "PRAZO VENCIDO"),
                            (
                                "LINHA TOTALMENTE REMANEJADA",
                                "LINHA TOTALMENTE REMANEJADA",
                            ),
                            (
                                "LINHA TOTALMENTE EXECUTADA",
                                "LINHA TOTALMENTE EXECUTADA",
                            ),
                            ("LINHA DE PAGAMENTO", "LINHA DE PAGAMENTO"),
                            (
                                "LINHA PARCIALMENTE REMANEJADA",
                                "LINHA PARCIALMENTE REMANEJADA",
                            ),
                            (
                                "LINHA PARCIALMENTE EXECUTADA",
                                "LINHA PARCIALMENTE EXECUTADA",
                            ),
                            ("N/A", "N/A"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Status do Contrato",
                    ),
                ),
                (
                    "contract_notes",
                    models.TextField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        max_length=500, verbose_name="Motivo da Alteração"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "budget_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="budgetline.budgetline",
                        verbose_name="Linha Orçamentária",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_line_versions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "main_fiscal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="main_fiscal_versions",
                        to="employee.employee",
                        verbose_name="Fiscal Principal",
                    ),
                ),
                (
                    "management_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_line_versions",
                        to="center.managementcenter",
                        verbose_name="Centro de Gestor",
                    ),
                ),
                (
                    "requesting_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="center.requestingcenter",
                        verbose_name="Centro Solicitante",
                    ),
                ),
                (
                    "secondary_fiscal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secondary_fiscal_versions",
                        to="employee.employee",
                        verbose_name="Fiscal Substituto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão de Linha Orçamentária",
                "verbose_name_plural": "Versões de Linhas Orçamentárias",
                "ordering": ["-version_number"],
                "unique_together": {("budget_line", "version_number")},
            },
        ),
    ]
