# Generated by Django 5.2.7 on 2026-08-02 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('BUDGET', 'Orçamento'), ('BUDGET_LINE', 'Linha Orçamentária'), ('CONTRACT', 'Contrato')], max_length=20, verbose_name='Tipo de Recurso')),
                ('resource_id', models.PositiveIntegerField(verbose_name='ID do Recurso')),
                ('resource_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Recurso')),
                ('invited_email', models.EmailField(max_length=254, verbose_name='E-mail do Convidado')),
                ('permission_type', models.CharField(choices=[('VIEW', 'Somente Visualização'), ('CREATE_BUDGET_LINES', 'Pode Criar Linhas Orçamentárias'), ('CREATE_CONTRACTS', 'Pode Criar Contratos')], default='VIEW', max_length=25, verbose_name='Tipo de Permissão')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceito'), ('REVOKED', 'Revogado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=10, verbose_name='Status')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_received', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Convidado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_given', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Compartilhamento',
                'verbose_name_plural': 'Compartilhamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SHARE_RECEIVED', 'Compartilhamento recebido'), ('SHARE_REVOKED', 'Compartilhamento revogado')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_notifications', to='sharing.resourceshare', verbose_name='Compartilhamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação de Compartilhamento',
                'verbose_name_plural': 'Notificações de Compartilhamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resourceshare',
            index=models.Index(fields=['resource_type', 'resource_id', 'status'], name='share_resource_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceshare',
            index=models.Index(fields=['invited_email', 'status'], name='share_email_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceshare',
            index=models.Index(fields=['owner', 'status'], name='share_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceshare',
            index=models.Index(fields=['invited_user', 'status'], name='share_invited_user_idx'),
        ),
        migrations.AddIndex(
            model_name='sharenotification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='share_notif_user_read_idx'),
        ),
    ]
