# Generated by Django 5.2.7 on 2026-01-25 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("SCHEMA", "Schema do Banco"),
                            ("BUSINESS_RULE", "Regra de Negócio"),
                            ("FAQ", "Perguntas Frequentes"),
                            ("CONTEXT", "Contexto do Sistema"),
                            ("QUERY_EXAMPLE", "Exemplo de Consulta"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("content", models.TextField(verbose_name="Conteúdo")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadados"
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Embedding (JSON fallback)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Embedding de Documento",
                "verbose_name_plural": "Embeddings de Documentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_summary",
                    models.TextField(verbose_name="Resumo do Conteúdo"),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Embedding (JSON fallback)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="ai_assistant.conversationmessage",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="ai_assistant.conversationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding de Conversa",
                "verbose_name_plural": "Embeddings de Conversas",
                "ordering": ["-created_at"],
            },
        ),
    ]
