# Generated by Django 5.2.7 on 2026-01-10 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sector", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Nome completo"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                ("cpf", models.CharField(max_length=15, verbose_name="CPF")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Matrícula"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Cargo"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "admission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Admissão"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Logradouro"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cidade"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Estado"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="CEP"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome do Banco",
                    ),
                ),
                (
                    "bank_agency",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Agência"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Conta"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ATIVO", "Ativo"), ("INATIVO", "Inativo")],
                        default="ATIVO",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coordination",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sector.coordination",
                        verbose_name="Coordenação",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sector.direction",
                        verbose_name="Direção",
                    ),
                ),
                (
                    "management",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sector.management",
                        verbose_name="Gerência",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
                "indexes": [
                    models.Index(fields=["email"], name="employee_email_idx"),
                    models.Index(fields=["cpf"], name="employee_cpf_idx"),
                    models.Index(fields=["status"], name="employee_status_idx"),
                    models.Index(fields=["direction"], name="employee_direction_idx"),
                    models.Index(fields=["management"], name="employee_management_idx"),
                    models.Index(
                        fields=["coordination"], name="employee_coordination_idx"
                    ),
                ],
            },
        ),
    ]
